import type { MantineColor } from '@mantine/core';

// todo: can we use Mantine ContextMenu as an external dependency?
export type DataTableContextMenuItemProps = {
  /**
   * Unique item key.
   */
  key: string;
} & (
  | {
      icon?: never;
      title?: never;
      color?: never;
      hidden?: never;
      disabled?: never;
      onClick?: never;
    }
  | {
      /**
       * Item icon
       */
      icon?: React.ReactNode;

      /**
       * Item title; if not present, one will be generated by "humanizing"
       * the provided item key.
       * (i.e. `viewRecord` -> `View record`)
       */
      title?: React.ReactNode;

      /**
       * Item color.
       */
      color?: MantineColor;

      /**
       * if true, the menu item will not be shown.
       */
      hidden?: boolean;

      /**
       * if true, the menu item will be disabled.
       */
      disabled?: boolean;

      /**
       * Function to call when the menu item is clicked.
       */
      onClick: () => void;
    }
);
