import type {
  CollapseProps,
  DefaultProps,
  MantineColor,
  MantineNumberSize,
  MantineShadow,
  MantineSize,
  MantineTheme,
  Sx,
  TableProps,
} from '@mantine/core';
import type { CSSProperties, ReactNode } from 'react';

export type DataTableColumnTextAlignment = 'left' | 'center' | 'right';
export type DataTableVerticalAlignment = 'top' | 'center' | 'bottom';

export type DataTableOuterBorderProps =
  | {
      withBorder?: never;
      borderRadius?: never;
    }
  | {
      /**
       * If true, table will have border
       */
      withBorder: boolean;

      /**
       * Table border radius
       */
      borderRadius?: MantineNumberSize;
    };

export type DataTableEmptyStateProps =
  | {
      /**
       * Content to show when no records are available; the provided content
       * will be overlaid and centered automatically
       */
      emptyState?: ReactNode;

      noRecordsText?: never;
      noRecordsIcon?: never;
    }
  | {
      emptyState?: never;

      /**
       * Text to show when no records are available
       */
      noRecordsText?: string;

      /**
       * Icon to show when no records are available
       */
      noRecordsIcon?: ReactNode;
    };

export type DataTablePaginationProps =
  | {
      page?: never;
      onPageChange?: never;
      totalRecords?: never;
      recordsPerPage?: never;
      paginationSize?: never;
      paginationText?: never;
    }
  | {
      /**
       * Current page number (1-based); if provided, a pagination component is shown
       */
      page: number;

      /**
       * Callback fired after change of each page
       */
      onPageChange: (page: number) => void;

      /**
       * Total number of records in the dataset
       */
      totalRecords: number | undefined;

      /**
       * Number of records per page
       */
      recordsPerPage: number;

      /**
       * Pagination component size; defaults to `sm`
       */
      paginationSize?: MantineSize;

      /**
       * Pagination text; defaults to ```({ from, to, totalRecords }) => `${from}-${to}/${totalRecords}`
       * ```
       */
      paginationText?: (options: { from: number; to: number; totalRecords: number }) => ReactNode;
    };

export type DataTableColumn<T> = {
  /**
   * Column accessor; you can use dot-notation for nested objects property drilling
   * (i.e. `department.name` or `department.company.name`)
   */
  accessor: string;

  /**
   * If set, the column will only be visible according to the specified media query
   */
  visibleMediaQuery?: string | ((theme: MantineTheme) => string);

  /**
   * Optional column header title; if not present, one will be generated by "humanizing"
   * the provided column accessor
   * (i.e. `firstName` -> `First name`; `user.firstName` -> `User first name`)
   */
  title?: ReactNode;

  /**
   * Custom cell data render function accepting the current record
   */
  render?: (record: T) => ReactNode;

  /**
   * Column text alignment; defaults to `left`
   */
  textAlignment?: DataTableColumnTextAlignment;

  /**
   * If true, column will be sortable
   */
  sortable?: boolean;

  /**
   * Desired column width
   */
  width?: string | number;

  /**
   * If true, cell content in this column will be truncated with ellipsis as needed
   */
  ellipsis?: boolean;

  /**
   * Optional class name passed to each data cell in the column; can be a string or a function
   * receiving the current record as its argument and returning a string
   */
  cellsClassName?: string | ((record: T) => string | undefined);

  /**
   * Optional style passed to each data cell in the column; can be a CSS properties object or
   * a function receiving the current record as its argument and returning a CSS properties object
   */
  cellsStyle?: CSSProperties | ((record: T) => CSSProperties | undefined);

  /**
   * Optional style passed to each data cell in the column; see https://mantine.dev/styles/sx/
   */
  cellsSx?: Sx;
};

export type DataTableSortStatus = {
  /**
   * Sort column accessor; you can use dot-notation for nested objects property drilling
   * (i.e. `department.name` or `department.company.name`)
   */
  columnAccessor: string;

  /**
   * Sort direction; `asc` for ascending or `desc` for descending
   */
  direction: 'asc' | 'desc';
};

export type DataTableSortProps =
  | {
      sortStatus?: never;
      onSortStatusChange?: never;
    }
  | {
      /**
       * Current sort status (sort column accessor & direction)
       */
      sortStatus: DataTableSortStatus;

      /**
       * Callback fired after change of sort status
       */
      onSortStatusChange?: (sortStatus: DataTableSortStatus) => void;
    };

export type DataTableSelectionProps<T> =
  | {
      selectedRecords?: never;
      onSelectedRecordsChange?: never;
    }
  | {
      /**
       * Currently-selected records
       */
      selectedRecords: T[];

      /**
       * Callback fired after change of selected records
       */
      onSelectedRecordsChange?: (selectedRecords: T[]) => void;
    };

export type DataTableContextMenuItemProps =
  | {
      /**
       * Unique item key
       */
      key: string;
    } & (
      | {
          /**
           * If true, insert an actions divider
           */
          divider: true;
          icon?: never;
          title?: never;
          color?: never;
          hidden?: never;
          disabled?: never;
          onClick?: never;
        }
      | {
          divider?: never;
          /**
           * Item icon
           */
          icon?: ReactNode;

          /**
           * Item title; if not present, one will be generated by "humanizing"
           * the provided item key
           * (i.e. `viewRecord` -> `View record`)
           */
          title?: ReactNode;

          /**
           * Item color
           */
          color?: MantineColor;

          /**
           * if true, the menu item will not be shown
           */
          hidden?: boolean;

          /**
           * if true, the menu item will be disabled
           */
          disabled?: boolean;

          /**
           * Function to call when the menu item is clicked
           */
          onClick: () => void;
        }
    );

export type ExpandedRowCollapseProps = Pick<
  CollapseProps,
  'animateOpacity' | 'transitionDuration' | 'transitionTimingFunction'
>;

type ExpandedRowProps<T> = {
  /**
   * Defines when rows should expand; defaults to `click`
   * May pass a custom function that receives the current record;
   * if true, that row will be expanded
   */
  expandRowOn?: 'click' | 'always' | ((record: T) => boolean);

  /**
   * Defined if multiple rows are allowed to be expanded at the same time; defaults to `false`
   */
  expandMultiple?: boolean;

  /**
   * Defines the record that will be expanded when the table is first loaded;
   * defaults to `undefined`;
   * does nothing if `expandRowOn === 'always'`
   */
  expandFirst?: unknown;

  /**
   * Pass additional props to the Mantine Collapse component wrapping the custom component;
   * does not accept the `children`, `in`, or `onTransitionEnd` properties
   */
  collapseProps?: ExpandedRowCollapseProps;

  /**
   * Custom component to be rendered;
   * accepts the current record
   */
  item: (record: T) => ReactNode;
};

export type DataTableProps<T> = {
  /**
   * Table height; defaults to `100%`
   */
  height?: string | number;

  /**
   * Minimum table height
   */
  minHeight?: string | number;

  /**
   * `DataTable` component shadow
   */
  shadow?: MantineShadow;

  /**
   * If true, columns will have vertical borders
   */
  withColumnBorders?: boolean;

  /**
   * Table border color, applied to the outer border, the header bottom border, and the pagination
   * footer top border; defaults to
   * `(theme) => (theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3])`
   */
  borderColor?: string | ((theme: MantineTheme) => string);

  /**
   * Row border color; defaults to
   * `(theme) => (theme.fn.rgba(theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3], 0.65))`
   */
  rowBorderColor?: string | ((theme: MantineTheme) => string);

  /**
   * If true, the user will not be able to select text
   */
  textSelectionDisabled?: boolean;

  /**
   * Vertical alignment for row cells; defaults to `center`
   */
  verticalAlignment?: DataTableVerticalAlignment;

  /**
   * If true, will show a loader with semi-transparent background, centered over the table
   */
  fetching?: boolean;

  /**
   * Visible columns
   */
  columns: DataTableColumn<T>[];

  /**
   * Accessor to use as unique record key; you can use dot-notation for nested objects property drilling
   * (i.e. `department.name` or `department.company.name`);
   * defaults to `id`
   */
  idAccessor?: string;

  /**
   * Visible records; the `DataTable` component will try to infer its row type from here
   */
  records?: T[];

  /**
   * Loader size; defaults to `lg`
   */
  loaderSize?: MantineNumberSize;

  /**
   * Loader variant
   */
  loaderVariant?: MantineTheme['loader'];

  /**
   * Loader background blur (in pixels)
   */
  loaderBackgroundBlur?: number;

  /**
   * Function to call when a row is clicked
   */
  onRowClick?: (record: T) => void;

  /**
   * Defines a context-menu menu to show when user right-clicks or clicks on a row
   */
  rowContextMenu?: {
    /**
     * Context menu trigger; defaults to `rightClick` for classic behavior
     */
    trigger?: 'rightClick' | 'click';

    /**
     * Menu z-index; defaults to `3`
     */
    zIndex?: number;

    /**
     * Menu border radius; defaults to `xs`
     */
    borderRadius?: MantineNumberSize;

    /**
     * Menu shadow; defaults to `sm`
     */
    shadow?: MantineShadow;

    /**
     * Boolean or function accepting the current record as parameter returning boolean;
     * if true, the menu will not be shown
     */
    hidden?: boolean | ((record: T) => boolean);

    /**
     * A function returning the row menu items for the current record
     */
    items: (record: T) => DataTableContextMenuItemProps[];
  };

  /**
   * Defines a custom component to render beneath the related record's row
   */
  expandedRow?: ExpandedRowProps<T>;
} & Pick<TableProps, 'striped' | 'highlightOnHover' | 'horizontalSpacing' | 'verticalSpacing' | 'fontSize'> &
  Omit<DefaultProps<'root' | 'header' | 'pagination', CSSProperties>, 'unstyled'> &
  DataTableOuterBorderProps &
  DataTableEmptyStateProps &
  DataTablePaginationProps &
  DataTableSortProps &
  DataTableSelectionProps<T>;
